require File.join(File.dirname(__FILE__), "spec_helper.rb")
require 'rake'
require 'rspec/core/rake_task'

desc "Run integration tests"
RSpec::Core::RakeTask.new(:integration) do |t|
    t.pattern = '*_test.rb'
    t.rspec_opts = File.read("spec.opts").chomp
end

task :default => [:integration]
